#!/bin/bash
set -x
set -e

MEM=${1:-"8192M"}
RSYNC_OPT=" --update "
[ -n "${INIT_WORLD:-}" ] && RSYNC_OPT=" --delete "

rsync -a $RSYNC_OPT /opt/minecraft/ /minecraft/
cd /minecraft
[ -n "${ONLINE_MODE:-}" ] && sed -i -e "s/^online-mode=.*/online-mode=$ONLINE_MODE/g" /minecraft/server.properties

/etc/init.d/ssh start
echo "jsp classroom on" | /usr/bin/java -Xmx"${MEM}" -jar CraftBukkit/target/craftbukkit-${MINECRAFT_VERSION}-R0.1-SNAPSHOT.jar
